package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONVERSATION".
 */
public class Conversation {

    private String conversationId;
    private String membersId;
    private String createrId;
    private java.util.Date last_message_time;
    private String last_message;
    private boolean silent;
    private String cache_message;

    public Conversation() {
    }

    public Conversation(String conversationId) {
        this.conversationId = conversationId;
    }

    public Conversation(String conversationId, String membersId, String createrId, java.util.Date last_message_time, String last_message, boolean silent, String cache_message) {
        this.conversationId = conversationId;
        this.membersId = membersId;
        this.createrId = createrId;
        this.last_message_time = last_message_time;
        this.last_message = last_message;
        this.silent = silent;
        this.cache_message = cache_message;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getMembersId() {
        return membersId;
    }

    public void setMembersId(String membersId) {
        this.membersId = membersId;
    }

    public String getCreaterId() {
        return createrId;
    }

    public void setCreaterId(String createrId) {
        this.createrId = createrId;
    }

    public java.util.Date getLast_message_time() {
        return last_message_time;
    }

    public void setLast_message_time(java.util.Date last_message_time) {
        this.last_message_time = last_message_time;
    }

    public String getLast_message() {
        return last_message;
    }

    public void setLast_message(String last_message) {
        this.last_message = last_message;
    }

    public boolean getSilent() {
        return silent;
    }

    public void setSilent(boolean silent) {
        this.silent = silent;
    }

    public String getCache_message() {
        return cache_message;
    }

    public void setCache_message(String cache_message) {
        this.cache_message = cache_message;
    }

}
