package com.coband.watchassistant;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.coband.watchassistant.TodayData;
import com.coband.watchassistant.User;
import com.coband.watchassistant.Follower;
import com.coband.watchassistant.Followee;
import com.coband.watchassistant.PushApp;
import com.coband.watchassistant.HistoryData;
import com.coband.watchassistant.Card;
import com.coband.watchassistant.Sleep;
import com.coband.watchassistant.HeartRate;
import com.coband.watchassistant.DBWeight;
import com.coband.watchassistant.Conversation;
import com.coband.watchassistant.StepNodeDetail;
import com.coband.watchassistant.SleepNodeDetail;
import com.coband.watchassistant.BloodPressure;
import com.coband.watchassistant.Account;

import com.coband.watchassistant.TodayDataDao;
import com.coband.watchassistant.UserDao;
import com.coband.watchassistant.FollowerDao;
import com.coband.watchassistant.FolloweeDao;
import com.coband.watchassistant.PushAppDao;
import com.coband.watchassistant.HistoryDataDao;
import com.coband.watchassistant.CardDao;
import com.coband.watchassistant.SleepDao;
import com.coband.watchassistant.HeartRateDao;
import com.coband.watchassistant.DBWeightDao;
import com.coband.watchassistant.ConversationDao;
import com.coband.watchassistant.StepNodeDetailDao;
import com.coband.watchassistant.SleepNodeDetailDao;
import com.coband.watchassistant.BloodPressureDao;
import com.coband.watchassistant.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todayDataDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig followerDaoConfig;
    private final DaoConfig followeeDaoConfig;
    private final DaoConfig pushAppDaoConfig;
    private final DaoConfig historyDataDaoConfig;
    private final DaoConfig cardDaoConfig;
    private final DaoConfig sleepDaoConfig;
    private final DaoConfig heartRateDaoConfig;
    private final DaoConfig dBWeightDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig stepNodeDetailDaoConfig;
    private final DaoConfig sleepNodeDetailDaoConfig;
    private final DaoConfig bloodPressureDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final TodayDataDao todayDataDao;
    private final UserDao userDao;
    private final FollowerDao followerDao;
    private final FolloweeDao followeeDao;
    private final PushAppDao pushAppDao;
    private final HistoryDataDao historyDataDao;
    private final CardDao cardDao;
    private final SleepDao sleepDao;
    private final HeartRateDao heartRateDao;
    private final DBWeightDao dBWeightDao;
    private final ConversationDao conversationDao;
    private final StepNodeDetailDao stepNodeDetailDao;
    private final SleepNodeDetailDao sleepNodeDetailDao;
    private final BloodPressureDao bloodPressureDao;
    private final AccountDao accountDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todayDataDaoConfig = daoConfigMap.get(TodayDataDao.class).clone();
        todayDataDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        followerDaoConfig = daoConfigMap.get(FollowerDao.class).clone();
        followerDaoConfig.initIdentityScope(type);

        followeeDaoConfig = daoConfigMap.get(FolloweeDao.class).clone();
        followeeDaoConfig.initIdentityScope(type);

        pushAppDaoConfig = daoConfigMap.get(PushAppDao.class).clone();
        pushAppDaoConfig.initIdentityScope(type);

        historyDataDaoConfig = daoConfigMap.get(HistoryDataDao.class).clone();
        historyDataDaoConfig.initIdentityScope(type);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        sleepDaoConfig = daoConfigMap.get(SleepDao.class).clone();
        sleepDaoConfig.initIdentityScope(type);

        heartRateDaoConfig = daoConfigMap.get(HeartRateDao.class).clone();
        heartRateDaoConfig.initIdentityScope(type);

        dBWeightDaoConfig = daoConfigMap.get(DBWeightDao.class).clone();
        dBWeightDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        stepNodeDetailDaoConfig = daoConfigMap.get(StepNodeDetailDao.class).clone();
        stepNodeDetailDaoConfig.initIdentityScope(type);

        sleepNodeDetailDaoConfig = daoConfigMap.get(SleepNodeDetailDao.class).clone();
        sleepNodeDetailDaoConfig.initIdentityScope(type);

        bloodPressureDaoConfig = daoConfigMap.get(BloodPressureDao.class).clone();
        bloodPressureDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        todayDataDao = new TodayDataDao(todayDataDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        followerDao = new FollowerDao(followerDaoConfig, this);
        followeeDao = new FolloweeDao(followeeDaoConfig, this);
        pushAppDao = new PushAppDao(pushAppDaoConfig, this);
        historyDataDao = new HistoryDataDao(historyDataDaoConfig, this);
        cardDao = new CardDao(cardDaoConfig, this);
        sleepDao = new SleepDao(sleepDaoConfig, this);
        heartRateDao = new HeartRateDao(heartRateDaoConfig, this);
        dBWeightDao = new DBWeightDao(dBWeightDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        stepNodeDetailDao = new StepNodeDetailDao(stepNodeDetailDaoConfig, this);
        sleepNodeDetailDao = new SleepNodeDetailDao(sleepNodeDetailDaoConfig, this);
        bloodPressureDao = new BloodPressureDao(bloodPressureDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(TodayData.class, todayDataDao);
        registerDao(User.class, userDao);
        registerDao(Follower.class, followerDao);
        registerDao(Followee.class, followeeDao);
        registerDao(PushApp.class, pushAppDao);
        registerDao(HistoryData.class, historyDataDao);
        registerDao(Card.class, cardDao);
        registerDao(Sleep.class, sleepDao);
        registerDao(HeartRate.class, heartRateDao);
        registerDao(DBWeight.class, dBWeightDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(StepNodeDetail.class, stepNodeDetailDao);
        registerDao(SleepNodeDetail.class, sleepNodeDetailDao);
        registerDao(BloodPressure.class, bloodPressureDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        todayDataDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        followerDaoConfig.getIdentityScope().clear();
        followeeDaoConfig.getIdentityScope().clear();
        pushAppDaoConfig.getIdentityScope().clear();
        historyDataDaoConfig.getIdentityScope().clear();
        cardDaoConfig.getIdentityScope().clear();
        sleepDaoConfig.getIdentityScope().clear();
        heartRateDaoConfig.getIdentityScope().clear();
        dBWeightDaoConfig.getIdentityScope().clear();
        conversationDaoConfig.getIdentityScope().clear();
        stepNodeDetailDaoConfig.getIdentityScope().clear();
        sleepNodeDetailDaoConfig.getIdentityScope().clear();
        bloodPressureDaoConfig.getIdentityScope().clear();
        accountDaoConfig.getIdentityScope().clear();
    }

    public TodayDataDao getTodayDataDao() {
        return todayDataDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FollowerDao getFollowerDao() {
        return followerDao;
    }

    public FolloweeDao getFolloweeDao() {
        return followeeDao;
    }

    public PushAppDao getPushAppDao() {
        return pushAppDao;
    }

    public HistoryDataDao getHistoryDataDao() {
        return historyDataDao;
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public SleepDao getSleepDao() {
        return sleepDao;
    }

    public HeartRateDao getHeartRateDao() {
        return heartRateDao;
    }

    public DBWeightDao getDBWeightDao() {
        return dBWeightDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public StepNodeDetailDao getStepNodeDetailDao() {
        return stepNodeDetailDao;
    }

    public SleepNodeDetailDao getSleepNodeDetailDao() {
        return sleepNodeDetailDao;
    }

    public BloodPressureDao getBloodPressureDao() {
        return bloodPressureDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
