package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBWEIGHT".
 */
public class DBWeight {

    private Long id;
    private float weight;
    private float bodyMI;
    private boolean upload;
    private long date;
    /** Not-null value. */
    private String uid;

    public DBWeight() {
    }

    public DBWeight(Long id) {
        this.id = id;
    }

    public DBWeight(Long id, float weight, float bodyMI, boolean upload, long date, String uid) {
        this.id = id;
        this.weight = weight;
        this.bodyMI = bodyMI;
        this.upload = upload;
        this.date = date;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public float getBodyMI() {
        return bodyMI;
    }

    public void setBodyMI(float bodyMI) {
        this.bodyMI = bodyMI;
    }

    public boolean getUpload() {
        return upload;
    }

    public void setUpload(boolean upload) {
        this.upload = upload;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

}
