package com.coband.watchassistant;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.coband.watchassistant.HeartRate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HEART_RATE".
*/
public class HeartRateDao extends AbstractDao<HeartRate, Long> {

    public static final String TABLENAME = "HEART_RATE";

    /**
     * Properties of entity HeartRate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, long.class, "date", false, "DATE");
        public final static Property HeartRate = new Property(2, String.class, "heartRate", false, "HEART_RATE");
        public final static Property Upload = new Property(3, boolean.class, "upload", false, "UPLOAD");
        public final static Property Uid = new Property(4, String.class, "uid", false, "UID");
    };


    public HeartRateDao(DaoConfig config) {
        super(config);
    }
    
    public HeartRateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HEART_RATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE\" INTEGER NOT NULL UNIQUE ," + // 1: date
                "\"HEART_RATE\" TEXT," + // 2: heartRate
                "\"UPLOAD\" INTEGER NOT NULL ," + // 3: upload
                "\"UID\" TEXT NOT NULL );"); // 4: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HEART_RATE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HeartRate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDate());
 
        String heartRate = entity.getHeartRate();
        if (heartRate != null) {
            stmt.bindString(3, heartRate);
        }
        stmt.bindLong(4, entity.getUpload() ? 1L: 0L);
        stmt.bindString(5, entity.getUid());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HeartRate readEntity(Cursor cursor, int offset) {
        HeartRate entity = new HeartRate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // heartRate
            cursor.getShort(offset + 3) != 0, // upload
            cursor.getString(offset + 4) // uid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HeartRate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getLong(offset + 1));
        entity.setHeartRate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUpload(cursor.getShort(offset + 3) != 0);
        entity.setUid(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HeartRate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HeartRate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
