package com.coband.watchassistant;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.coband.watchassistant.HistoryData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY_DATA".
*/
public class HistoryDataDao extends AbstractDao<HistoryData, Long> {

    public static final String TABLENAME = "HISTORY_DATA";

    /**
     * Properties of entity HistoryData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, long.class, "date", false, "DATE");
        public final static Property Step = new Property(2, long.class, "step", false, "STEP");
        public final static Property Distance = new Property(3, float.class, "distance", false, "DISTANCE");
        public final static Property Calories = new Property(4, float.class, "calories", false, "CALORIES");
        public final static Property Time = new Property(5, long.class, "time", false, "TIME");
        public final static Property Upload = new Property(6, boolean.class, "upload", false, "UPLOAD");
        public final static Property Target = new Property(7, long.class, "target", false, "TARGET");
        public final static Property TargetFinish = new Property(8, boolean.class, "targetFinish", false, "TARGET_FINISH");
        public final static Property Uid = new Property(9, String.class, "uid", false, "UID");
    };


    public HistoryDataDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DATE\" INTEGER NOT NULL ," + // 1: date
                "\"STEP\" INTEGER NOT NULL ," + // 2: step
                "\"DISTANCE\" REAL NOT NULL ," + // 3: distance
                "\"CALORIES\" REAL NOT NULL ," + // 4: calories
                "\"TIME\" INTEGER NOT NULL ," + // 5: time
                "\"UPLOAD\" INTEGER NOT NULL ," + // 6: upload
                "\"TARGET\" INTEGER NOT NULL ," + // 7: target
                "\"TARGET_FINISH\" INTEGER NOT NULL ," + // 8: targetFinish
                "\"UID\" TEXT NOT NULL );"); // 9: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HistoryData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDate());
        stmt.bindLong(3, entity.getStep());
        stmt.bindDouble(4, entity.getDistance());
        stmt.bindDouble(5, entity.getCalories());
        stmt.bindLong(6, entity.getTime());
        stmt.bindLong(7, entity.getUpload() ? 1L: 0L);
        stmt.bindLong(8, entity.getTarget());
        stmt.bindLong(9, entity.getTargetFinish() ? 1L: 0L);
        stmt.bindString(10, entity.getUid());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HistoryData readEntity(Cursor cursor, int offset) {
        HistoryData entity = new HistoryData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // date
            cursor.getLong(offset + 2), // step
            cursor.getFloat(offset + 3), // distance
            cursor.getFloat(offset + 4), // calories
            cursor.getLong(offset + 5), // time
            cursor.getShort(offset + 6) != 0, // upload
            cursor.getLong(offset + 7), // target
            cursor.getShort(offset + 8) != 0, // targetFinish
            cursor.getString(offset + 9) // uid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HistoryData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getLong(offset + 1));
        entity.setStep(cursor.getLong(offset + 2));
        entity.setDistance(cursor.getFloat(offset + 3));
        entity.setCalories(cursor.getFloat(offset + 4));
        entity.setTime(cursor.getLong(offset + 5));
        entity.setUpload(cursor.getShort(offset + 6) != 0);
        entity.setTarget(cursor.getLong(offset + 7));
        entity.setTargetFinish(cursor.getShort(offset + 8) != 0);
        entity.setUid(cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HistoryData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HistoryData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
