package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY_DATA".
 */
public class HistoryData {

    private Long id;
    private long date;
    private long step;
    private float distance;
    private float calories;
    private long time;
    private boolean upload;
    private long target;
    private boolean targetFinish;
    /** Not-null value. */
    private String uid;

    public HistoryData() {
    }

    public HistoryData(Long id) {
        this.id = id;
    }

    public HistoryData(Long id, long date, long step, float distance, float calories, long time, boolean upload, long target, boolean targetFinish, String uid) {
        this.id = id;
        this.date = date;
        this.step = step;
        this.distance = distance;
        this.calories = calories;
        this.time = time;
        this.upload = upload;
        this.target = target;
        this.targetFinish = targetFinish;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public long getStep() {
        return step;
    }

    public void setStep(long step) {
        this.step = step;
    }

    public float getDistance() {
        return distance;
    }

    public void setDistance(float distance) {
        this.distance = distance;
    }

    public float getCalories() {
        return calories;
    }

    public void setCalories(float calories) {
        this.calories = calories;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public boolean getUpload() {
        return upload;
    }

    public void setUpload(boolean upload) {
        this.upload = upload;
    }

    public long getTarget() {
        return target;
    }

    public void setTarget(long target) {
        this.target = target;
    }

    public boolean getTargetFinish() {
        return targetFinish;
    }

    public void setTargetFinish(boolean targetFinish) {
        this.targetFinish = targetFinish;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

}
