package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SLEEP_NODE_DETAIL".
 */
public class SleepNodeDetail {

    private Long id;
    private long date;
    private int begin;
    private int mode;
    /** Not-null value. */
    private String uid;

    public SleepNodeDetail() {
    }

    public SleepNodeDetail(Long id) {
        this.id = id;
    }

    public SleepNodeDetail(Long id, long date, int begin, int mode, String uid) {
        this.id = id;
        this.date = date;
        this.begin = begin;
        this.mode = mode;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public int getBegin() {
        return begin;
    }

    public void setBegin(int begin) {
        this.begin = begin;
    }

    public int getMode() {
        return mode;
    }

    public void setMode(int mode) {
        this.mode = mode;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

}
