package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.support.annotation.NonNull;

/**
 * Entity mapped to table "SLEEP".
 */
public class Sleep {

    private Long id;
    private long date;
    private int deep;
    private int light;
    private int wakeCount;
    private int totalTime;
    private boolean upload;
    private String uid;
    private Integer beginTime;
    private Integer mode;

    public Sleep() {
    }

    public Sleep(Long id) {
        this.id = id;
    }

    public Sleep(Long id, long date, int deep, int light, int wakeCount, int totalTime, boolean upload, String uid, Integer beginTime, Integer mode) {
        this.id = id;
        this.date = date;
        this.deep = deep;
        this.light = light;
        this.wakeCount = wakeCount;
        this.totalTime = totalTime;
        this.upload = upload;
        this.uid = uid;
        this.beginTime = beginTime;
        this.mode = mode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public int getDeep() {
        return deep;
    }

    public void setDeep(int deep) {
        this.deep = deep;
    }

    public int getLight() {
        return light;
    }

    public void setLight(int light) {
        this.light = light;
    }

    public int getWakeCount() {
        return wakeCount;
    }

    public void setWakeCount(int wakeCount) {
        this.wakeCount = wakeCount;
    }

    public int getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(int totalTime) {
        this.totalTime = totalTime;
    }

    public boolean getUpload() {
        return upload;
    }

    public void setUpload(boolean upload) {
        this.upload = upload;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public Integer getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Integer beginTime) {
        this.beginTime = beginTime;
    }

    public Integer getMode() {
        return mode;
    }

    public void setMode(Integer mode) {
        this.mode = mode;
    }
}
