package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STEP_NODE_DETAIL".
 */
public class StepNodeDetail {

    private Long id;
    private long date;
    private int offset;
    private long step;
    private int calories;
    private int distance;
    /** Not-null value. */
    private String uid;

    public StepNodeDetail() {
    }

    public StepNodeDetail(Long id) {
        this.id = id;
    }

    public StepNodeDetail(Long id, long date, int offset, long step, int calories, int distance, String uid) {
        this.id = id;
        this.date = date;
        this.offset = offset;
        this.step = step;
        this.calories = calories;
        this.distance = distance;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public long getStep() {
        return step;
    }

    public void setStep(long step) {
        this.step = step;
    }

    public int getCalories() {
        return calories;
    }

    public void setCalories(int calories) {
        this.calories = calories;
    }

    public int getDistance() {
        return distance;
    }

    public void setDistance(int distance) {
        this.distance = distance;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

}
