package com.coband.watchassistant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODAY_DATA".
 */
public class TodayData {

    private Long id;
    private long date;
    private float cal;
    private float dis;
    private long step;
    private int node;
    private long tt;

    public TodayData() {
    }

    public TodayData(Long id) {
        this.id = id;
    }

    public TodayData(Long id, long date, float cal, float dis, long step, int node, long tt) {
        this.id = id;
        this.date = date;
        this.cal = cal;
        this.dis = dis;
        this.step = step;
        this.node = node;
        this.tt = tt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public float getCal() {
        return cal;
    }

    public void setCal(float cal) {
        this.cal = cal;
    }

    public float getDis() {
        return dis;
    }

    public void setDis(float dis) {
        this.dis = dis;
    }

    public long getStep() {
        return step;
    }

    public void setStep(long step) {
        this.step = step;
    }

    public int getNode() {
        return node;
    }

    public void setNode(int node) {
        this.node = node;
    }

    public long getTt() {
        return tt;
    }

    public void setTt(long tt) {
        this.tt = tt;
    }

}
